# Generated by Django 4.2 on 2023-04-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_alter_list_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="text",
            field=models.TextField(default=None, null=True),
        ),
    ]
