# Generated by Django 4.2.3 on 2023-07-31 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=60, verbose_name="Заголовок новости"),
                ),
                ("content", models.TextField(verbose_name="Новость")),
                (
                    "weight",
                    models.FloatField(default=0, verbose_name="Рейтинг сложности"),
                ),
                ("source", models.TextField(verbose_name="Источник новости")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=main.utils.get_timestamp_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Выводить как список?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Опубликована"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор новости на сайте",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.subrubric",
                        verbose_name="Рубрика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdditionalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=main.utils.get_timestamp_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "new",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.news",
                        verbose_name="Новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Иллюстрация к новости",
                "verbose_name_plural": "Иллюстрации к новости",
            },
        ),
    ]
