# Generated by Django 4.2.3 on 2023-08-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_news_additionalimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=160, verbose_name="Заголовок новости"),
        ),
    ]
