# Generated by Django 4.2.3 on 2023-08-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="source",
            field=models.CharField(max_length=40, verbose_name="Источник"),
        ),
    ]
