# Generated by Django 4.2.4 on 2023-08-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="news",
            new_name="new",
        ),
    ]
