# Generated by Django 4.2.2 on 2023-06-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0002_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="", upload_to="images/%Y/%m/%d/"),
        ),
    ]
