#! /usr/bin/env python3

import csv 
from xml.etree.ElementTree import Element, SubElement, Comment, tostring
import datetime
from ElementTree_pretty import prettyfy

generated_on = str(datetime.datetime.now())

# configuration one attribute with method set()
root = Element('opml')
root.set('version', '1.0')

root.append(Comment('GEnerated by ElementTree_csv_to_xml.py for PyMOTW'))

head = SubElement(root, 'head')
title = SubElement(head, 'title')
title.text = 'My Podcasts'
dc = SubElement(head, 'dateCreated')
dc.text = generated_on
dm = SubElement(head, 'dateModified')
dm.text = generated_on

body = SubElement(root, 'body')

with open('podcasts.csv', 'rt', encoding='utf-8') as file_:
    current_group = None
    reader = csv.reader(file_)
    for row in reader:
        group_name, podcast_name, xml_url, html_url = row
        if (current_group is None or group_name != current_group.text):
            # begin new group
            current_group = SubElement(body, 'outline', {'text': group_name},)
            # added new podcast in group 
            # and set all attributes 
            podcast = SubElement(current_group, 'outline', 
                                 {'text': podcast_name, 
                                  'xmlUrl': xml_url, 
                                  'html_url': html_url},)
            
print(prettyfy(root))