# Generated by Django 4.2 on 2023-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_alter_item_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="text",
            field=models.TextField(default=None),
        ),
    ]
