// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGoNameHandlerFunc turns a function with the right signature into a get go name handler
type GetGoNameHandlerFunc func(GetGoNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGoNameHandlerFunc) Handle(params GetGoNameParams) middleware.Responder {
	return fn(params)
}

// GetGoNameHandler interface for that can handle valid get go name params
type GetGoNameHandler interface {
	Handle(GetGoNameParams) middleware.Responder
}

// NewGetGoName creates a new http.Handler for the get go name operation
func NewGetGoName(ctx *middleware.Context, handler GetGoNameHandler) *GetGoName {
	return &GetGoName{Context: ctx, Handler: handler}
}

/*
	GetGoName swagger:route GET /go/{name} getGoName

Return Go image.
*/
type GetGoName struct {
	Context *middleware.Context
	Handler GetGoNameHandler
}

func (o *GetGoName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGoNameParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
