// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetGoNameOKCode is the HTTP code returned for type GetGoNameOK
const GetGoNameOKCode int = 200

/*
GetGoNameOK Return Gother.

swagger:response getGoNameOK
*/
type GetGoNameOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetGoNameOK creates GetGoNameOK with default headers values
func NewGetGoNameOK() *GetGoNameOK {

	return &GetGoNameOK{}
}

// WithPayload adds the payload to the get go name o k response
func (o *GetGoNameOK) WithPayload(payload io.ReadCloser) *GetGoNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get go name o k response
func (o *GetGoNameOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGoNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
