# Generated by Django 4.2.3 on 2023-07-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advuser",
            old_name="is_activeted",
            new_name="is_activated",
        ),
    ]
