# Generated by Django 4.2.3 on 2023-07-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_is_activeted_advuser_is_activated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Название рубрики",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок рубрик"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubRubric",
            fields=[],
            options={
                "verbose_name": "Подрубрика",
                "verbose_name_plural": "Подрубрики",
                "ordering": (
                    "super_rubric__order",
                    "super_rubric__name",
                    "order",
                    "name",
                ),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.rubric",),
        ),
        migrations.CreateModel(
            name="SuperRubric",
            fields=[],
            options={
                "verbose_name": "Родительская рубрика",
                "verbose_name_plural": "Надрубрики",
                "ordering": ("order", "name"),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.rubric",),
        ),
        migrations.AddField(
            model_name="rubric",
            name="super_rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.superrubric",
                verbose_name="Родительская рубрика",
            ),
        ),
    ]
