// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server Go with Swagger endpoints documantation",
    "title": "rest_server",
    "version": "0.1.0"
  },
  "paths": {
    "/go/{name}": {
      "get": {
        "description": "Return Go image.",
        "produces": [
          "image/png"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "name of go to display.",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Return Gother.",
            "schema": {
              "type": "file"
            }
          }
        }
      }
    },
    "/healthz": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK message.",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    },
    "/hello/{user}": {
      "get": {
        "description": "Return user.",
        "parameters": [
          {
            "type": "string",
            "description": "name of user.",
            "name": "user",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Return the greet.",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Invalid name user."
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server Go with Swagger endpoints documantation",
    "title": "rest_server",
    "version": "0.1.0"
  },
  "paths": {
    "/go/{name}": {
      "get": {
        "description": "Return Go image.",
        "produces": [
          "image/png"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "name of go to display.",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Return Gother.",
            "schema": {
              "type": "file"
            }
          }
        }
      }
    },
    "/healthz": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK message.",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    },
    "/hello/{user}": {
      "get": {
        "description": "Return user.",
        "parameters": [
          {
            "type": "string",
            "description": "name of user.",
            "name": "user",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Return the greet.",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Invalid name user."
          }
        }
      }
    }
  }
}`))
}
