# Generated by Django 4.2.1 on 2023-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(
                help_text="Enter name", max_length=80, verbose_name="Enter name"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(verbose_name="Enter text"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="Enter short title", max_length=300, verbose_name="Title"
            ),
        ),
    ]
