# Generated by Django 4.2.1 on 2023-05-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_created_alter_post_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=300, unique_for_date="publish"),
        ),
    ]
