version: "2"

services:
  web:
    build: . 
    command: python /app_05/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app_05
    ports:
      - 8001:8001 
    depends_on:
      - db 
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lob/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
