version: "2"

services:
  web:
    build: . 
    command: python /app_08/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app_08
    ports:
      - 8000:8000 
    depends_on:
      - db 
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lob/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
    