# Generated by Django 4.2.1 on 2023-06-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="my_list",
            field=models.TextField(default=""),
        ),
    ]
