# Generated by Django 4.2.1 on 2023-06-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_item_my_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="my_list",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="lists.list",
            ),
        ),
    ]
