# Generated by Django 4.2.1 on 2023-06-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0006_alter_item_my_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="my_list",
        ),
    ]
