# Generated by Django 4.2.1 on 2023-06-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0007_remove_item_my_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="my_list",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="lists.list"
            ),
        ),
    ]
