# Generated by Django 4.2.2 on 2023-06-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
