# Generated by Django 4.0.1 on 2023-09-20 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', help_text='title product', max_length=100, verbose_name='title')),
                ('slug', models.SlugField(help_text='slug view', max_length=100, unique=True, verbose_name='slug name')),
                ('permiss', models.BooleanField(default=False, help_text='permission', verbose_name='permissions_for_user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_lesson', models.CharField(default='title', help_text='name of lesson', max_length=100, verbose_name='name_of_lesson')),
                ('video', models.URLField(help_text='url for video', max_length=400)),
                ('duration', models.FloatField(help_text='duration video in sec')),
                ('visited', models.BooleanField(default=False, help_text='show video')),
                ('current_time', models.FloatField(help_text='durration video visited')),
                ('lesson_to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app.product')),
            ],
        ),
    ]
