# Generated by Django 4.1.7 on 2023-03-26 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("startapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Title"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubric",
                "verbose_name_plural": "Rubric",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="appdb",
            options={
                "ordering": ["-published"],
                "verbose_name": "Обьявления",
                "verbose_name_plural": "Обьявления",
            },
        ),
        migrations.AlterField(
            model_name="appdb",
            name="content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание товара"
            ),
        ),
        migrations.AlterField(
            model_name="appdb",
            name="price",
            field=models.FloatField(blank=True, null=True, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="appdb",
            name="published",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="appdb",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Товар"),
        ),
        migrations.AddField(
            model_name="appdb",
            name="rubric",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="startapp.rubric",
                verbose_name="Rubric",
            ),
        ),
    ]
