# Generated by Django 4.0.4 on 2023-10-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(help_text='persona name', max_length=50, verbose_name='persona name')),
                ('your_last_name', models.CharField(help_text='last name', max_length=50, verbose_name='persona last name')),
                ('your_father', models.CharField(help_text='father name', max_length=40, verbose_name='father name')),
                ('avatar', models.FileField(help_text='avatar', upload_to='avatars', verbose_name='avatar')),
                ('age', models.IntegerField(default=18, help_text='age persona')),
                ('short_desc', models.TextField(default='', help_text='About you...', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='duration?')),
                ('name', models.CharField(help_text='name of vote', max_length=60, verbose_name='name')),
                ('begin', models.DateField(auto_now_add=True)),
                ('end', models.DateField()),
                ('max_votes', models.IntegerField(default=40)),
                ('persons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='vote.person')),
            ],
        ),
    ]
