# Generated by Django 4.0.4 on 2023-10-18 18:03

from django.db import migrations, models
import vote.models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_vote_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='is_active',
            field=models.BooleanField(default=vote.models.Vote.current_active_time, help_text='duration'),
        ),
    ]
