# Generated by Django 4.2.2 on 2023-06-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_text",
            field=models.BooleanField(default=False),
        ),
    ]
