# Generated by Django 4.2.2 on 2023-06-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(default="", max_length=300),
        ),
    ]
