# Generated by Django 4.2.2 on 2023-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_label", "0001_initial"),
        ("core_user", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="posts_liked",
            field=models.ManyToManyField(related_name="liked_by", to="core_label.post"),
        ),
    ]
