# Generated by Django 4.2.4 on 2023-08-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("album", "0002_song"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="number",
            new_name="in_album",
        ),
        migrations.AddField(
            model_name="song",
            name="number_in",
            field=models.IntegerField(default=1),
        ),
    ]
