version: '3'

services:
  web:
    build: .
    command: python /app_09/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app_09
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    restart: always
    image: postgres:16
    ports:
      - 5433:5433
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: