# Generated by Django 4.2.2 on 2023-06-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_id_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="uid",
            field=models.CharField(max_length=255),
        ),
    ]
