# Generated by Django 4.2.2 on 2023-06-13 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_token_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="uid",
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
